version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_URI: 'mongodb://adithya:narayan@localhost:8006/'
    ports:
      - 5000:5000
    volumes:
      - .:/app

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'adithya'
      MONGO_INITDB_ROOT_PASSWORD: 'narayan'
    ports:
      - 8006:27017
  
  mongoui:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'adithya'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'narayan'
      ME_CONFIG_MONGODB_URL: 'mongodb://adithya:naraya@db:27017/'

